In [31]:
import psycopg2
import pandas as pd
import numpy as np
from pathlib import Path
from collections import Counter

import warnings
warnings.filterwarnings('ignore')

In [32]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [22]:
engine = psycopg2.connect(
    database="project-data",
    user = "postgres",
    password = "Post23!Fnord",
    host = "happinessproject.cqkpnj5dcmou.us-east-1.rds.amazonaws.com",
    port = '5432'
    )

cursor = engine.cursor()

In [35]:
query = "SELECT * from worldhappinessreport_2021"

df = pd.read_sql(query, con=engine)

In [36]:
df.head()

,country_name,regional_indicator,ladder_score,stand_err,up_whisker,low_whisker,log_gdp_per_cap,social_support,healty_life_exp,freedom,generosity,percept_corrupt,ladder_score_distopia,expby_log_gdp_per_cap,expby_social_support,expby_healty_life_exp,expby_freedom,expby_generosity,expby_percept_corrupt,distopia_plus_resid
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [38]:
list(df)

['country_name',
 'regional_indicator',
 'ladder_score',
 'stand_err',
 'up_whisker',
 'low_whisker',
 'log_gdp_per_cap',
 'social_support',
 'healty_life_exp',
 'freedom',
 'generosity',
 'percept_corrupt',
 'ladder_score_distopia',
 'expby_log_gdp_per_cap',
 'expby_social_support',
 'expby_healty_life_exp',
 'expby_freedom',
 'expby_generosity',
 'expby_percept_corrupt',
 'distopia_plus_resid']

In [47]:
columns = [
    "regional_indicator", "stand_err", "up_whisker", "low_whisker",
    "log_gdp_per_cap", "social_support", "healty_life_exp", "freedom",
    "generosity", "percept_corrupt", "ladder_score_distopia", "expby_log_gdp_per_cap",
    "expby_social_support", "expby_healty_life_exp", "expby_freedom", "expby_generosity",
    "expby_percept_corrupt", "distopia_plus_resid"
]

target = ["ladder_score"]

In [49]:
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

df = df.astype({'ladder_score':'int'})

df.head()

,country_name,regional_indicator,ladder_score,stand_err,up_whisker,low_whisker,log_gdp_per_cap,social_support,healty_life_exp,freedom,generosity,percept_corrupt,ladder_score_distopia,expby_log_gdp_per_cap,expby_social_support,expby_healty_life_exp,expby_freedom,expby_generosity,expby_percept_corrupt,distopia_plus_resid
0,Finland,Western Europe,7,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [50]:
# Create our features
X = pd.get_dummies(df.drop(columns="ladder_score"))


# Create our target
y = df["ladder_score"]

In [51]:
X.describe()

,stand_err,up_whisker,low_whisker,log_gdp_per_cap,social_support,healty_life_exp,freedom,generosity,percept_corrupt,ladder_score_distopia,...,regional_indicator_Central and Eastern Europe,regional_indicator_Commonwealth of Independent States,regional_indicator_East Asia,regional_indicator_Latin America and Caribbean,regional_indicator_Middle East and North Africa,regional_indicator_North America and ANZ,regional_indicator_South Asia,regional_indicator_Southeast Asia,regional_indicator_Sub-Saharan Africa,regional_indicator_Western Europe
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,1.490000e+02,...,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,0.058752,5.648007,5.417631,9.432208,0.814745,64.992799,0.791597,-0.015134,0.727450,2.430000e+00,...,0.114094,0.080537,0.040268,0.134228,0.114094,0.026846,0.046980,0.060403,0.241611,0.140940
std,0.022001,1.054330,1.094879,1.158601,0.114889,6.762043,0.113332,0.150657,0.179226,5.347044e-15,...,0.318998,0.273040,0.197251,0.342047,0.318998,0.162177,0.212309,0.239035,0.429503,0.349133
min,0.026000,2.596000,2.449000,6.635000,0.463000,48.478000,0.382000,-0.288000,0.082000,2.430000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.043000,4.991000,4.706000,8.541000,0.750000,59.802000,0.718000,-0.126000,0.667000,2.430000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.054000,5.625000,5.413000,9.569000,0.832000,66.603000,0.804000,-0.036000,0.781000,2.430000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.070000,6.344000,6.128000,10.421000,0.905000,69.600000,0.877000,0.079000,0.845000,2.430000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.173000,7.904000,7.780000,11.647000,0.983000,76.953000,0.970000,0.542000,0.939000,2.430000e+00,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [52]:
# Check the balance of our target values
y.value_counts()

5    49
4    36
6    35
7    17
3    11
2     1
Name: ladder_score, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({6: 24, 4: 27, 3: 9, 5: 36, 7: 14, 2: 1})

In [54]:
# Resample the training data with the BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

# Creating a StandardScaler instance.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [55]:
# Calculated the balanced accuracy score
acc_score = balanced_accuracy_score(y_test, predictions)
acc_score

0.7106449106449106

In [56]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[ 0,  2,  0,  0,  0],
       [ 0,  8,  1,  0,  0],
       [ 0,  2, 11,  0,  0],
       [ 0,  0,  1,  9,  1],
       [ 0,  0,  0,  0,  3]], dtype=int64)

In [57]:
# Print the imbalanced classification report

from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

          3       0.00      0.00      1.00      0.00      0.00      0.00         2
          4       0.67      0.89      0.86      0.76      0.88      0.77         9
          5       0.85      0.85      0.92      0.85      0.88      0.77        13
          6       1.00      0.82      1.00      0.90      0.90      0.80        11
          7       0.75      1.00      0.97      0.86      0.99      0.97         3

avg / total       0.80      0.82      0.94      0.80      0.85      0.76        38

In [58]:
# List the features sorted in descending order by feature importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.1766702063964013, 'up_whisker'),
 (0.13434439279531768, 'low_whisker'),
 (0.05575446870788725, 'expby_log_gdp_per_cap'),
 (0.05280373581212532, 'social_support'),
 (0.052241679490766864, 'log_gdp_per_cap'),
 (0.04949232003240749, 'expby_healty_life_exp'),
 (0.04540131285614552, 'expby_freedom'),
 (0.04340832600034489, 'freedom'),
 (0.04313361221071999, 'healty_life_exp'),
 (0.041894551026841205, 'expby_social_support'),
 (0.03660720142934333, 'distopia_plus_resid'),
 (0.03621481434086348, 'expby_percept_corrupt'),
 (0.03528852388628428, 'stand_err'),
 (0.03456955871663419, 'percept_corrupt'),
 (0.021700957793525436, 'expby_generosity'),
 (0.021041387258017456, 'generosity'),
 (0.013533403532675563, 'regional_indicator_Western Europe'),
 (0.008820966408934277, 'regional_indicator_Middle East and North Africa'),
 (0.006693441726934331, 'regional_indicator_Central and Eastern Europe'),
 (0.00618356203496464, 'regional_indicator_Sub-Saharan Africa'),
 (0.0036029823250918803, 'country_name_Yemen'),
 (0.0032895506156126, 'country_name_Afghanistan'),
 (0.0030412210543107297, 'regional_indicator_North America and ANZ'),
 (0.002981285301014085, 'regional_indicator_East Asia'),
 (0.0029612539213928926, 'country_name_Costa Rica'),
 (0.0028200034528900533, 'country_name_Zimbabwe'),
 (0.002660415442831849,
  'regional_indicator_Commonwealth of Independent States'),
 (0.002336510505284232, 'regional_indicator_Southeast Asia'),
 (0.002271615521944599, 'regional_indicator_Latin America and Caribbean'),
 (0.0020208439917519566, 'country_name_Israel'),
 (0.0018734286193395706, 'country_name_Sri Lanka'),
 (0.0018567480113786145, 'country_name_Iceland'),
 (0.0018205663747751684, 'regional_indicator_South Asia'),
 (0.001706612181947082, 'country_name_Burundi'),
 (0.0016965400012704961, 'country_name_Kosovo'),
 (0.001475924789965898, 'country_name_Turkey'),
 (0.0012429657908191677, 'country_name_Brazil'),
 (0.001202842092855059, 'country_name_Sierra Leone'),
 (0.0011826471034695146, 'country_name_Mongolia'),
 (0.0011271137051763601, 'country_name_Ukraine'),
 (0.0011112339047809026, 'country_name_Uruguay'),
 (0.0010621034637479476, 'country_name_Niger'),
 (0.0010243531692209118, 'country_name_Tanzania'),
 (0.0009989212778274967, 'country_name_Haiti'),
 (0.0009349492072578397, 'country_name_Gambia'),
 (0.0009277863523419437, 'country_name_Rwanda'),
 (0.0009131382072868744, 'country_name_Congo (Brazzaville)'),
 (0.0008883554802932373, 'country_name_Cambodia'),
 (0.000844123371738308, 'country_name_Italy'),
 (0.0008385589772842713, 'country_name_Serbia'),
 (0.0008330277455373747, 'country_name_Mozambique'),
 (0.0008285027313695736, 'country_name_Uzbekistan'),
 (0.0008187186657443584, 'country_name_Togo'),
 (0.0007897297705485314, 'country_name_Germany'),
 (0.0007626049108264934, 'country_name_Bolivia'),
 (0.0007619671911031653, 'country_name_Namibia'),
 (0.0007127141351496437, 'country_name_Canada'),
 (0.0006874006344723141, 'country_name_Philippines'),
 (0.0006868562721510015, 'country_name_Hong Kong S.A.R. of China'),
 (0.0006846749835938891, 'country_name_New Zealand'),
 (0.0006619329374155777, 'country_name_Malawi'),
 (0.0006371256754569288, 'country_name_South Korea'),
 (0.0006310567617426787, 'country_name_Latvia'),
 (0.0006083997200011318, 'country_name_India'),
 (0.000596491772366319, 'country_name_Cyprus'),
 (0.0005791090369078818, 'country_name_Myanmar'),
 (0.000569197301795555, 'country_name_Mauritius'),
 (0.0005604055505176706, 'country_name_Greece'),
 (0.0005461342254614574, 'country_name_Jamaica'),
 (0.000529138572174794, 'country_name_Tunisia'),
 (0.0005224209642442279, 'country_name_Kuwait'),
 (0.0005223183421704631, 'country_name_Lithuania'),
 (0.0005188363234863003, 'country_name_Malta'),
 (0.0005174481325821303, 'country_name_Taiwan Province of China'),
 (0.0005119864289995371, 'country_name_Ghana'),
 (0.0005097144179575057, 'country_name_Switzerland'),
 (0.00049511895485675, 'country_name_France'),
 (0.0004925795477829393, 'country_name_Moldova'),
 (0.00047874666033700995, 'country_name_Peru'),
 (0.0004772979685350608, 'country_name_United Arab Emirates'),
 (0.00047556507046262673, 'country_name_Poland'),
 (0.00045952291229934113, 'country_name_Hungary'),
 (0.0004557606796659393, 'country_name_Bosnia and Herzegovina'),
 (0.00043226540112978204, 'country_name_Venezuela'),
 (0.0004307356135447354, 'country_name_Libya'),
 (0.00042614654571755716, 'country_name_Bahrain'),
 (0.00041010554765159044, 'country_name_United States'),
 (0.0003803053413867077, 'country_name_Iraq'),
 (0.00037890270067861135, 'country_name_Laos'),
 (0.00037732916304461934, 'country_name_Argentina'),
 (0.00036543371357785406, 'country_name_Malaysia'),
 (0.0003622304025627581, 'country_name_Nepal'),
 (0.0003563830939529573, 'country_name_Armenia'),
 (0.0003370054549424538, 'country_name_Uganda'),
 (0.00033680987457975446, 'country_name_Guinea'),
 (0.0003160079660346143, 'country_name_Palestinian Territories'),
 (0.00031118254670592756, 'country_name_Lebanon'),
 (0.00030963698477815563, 'country_name_Czech Republic'),
 (0.00030178943409159764, 'country_name_Netherlands'),
 (0.00029545258339623055, 'country_name_Montenegro'),
 (0.0002914078341417915, 'country_name_Dominican Republic'),
 (0.0002878128664744513, 'country_name_China'),
 (0.0002826543375374103, 'country_name_Finland'),
 (0.00026577978304798887, 'country_name_Pakistan'),
 (0.00025941724381313246, 'country_name_Bulgaria'),
 (0.0002586486963139249, 'country_name_Nigeria'),
 (0.0002497800365552508, 'country_name_Japan'),
 (0.0002377305725317599, 'country_name_Denmark'),
 (0.00023250607898066915, 'country_name_Ecuador'),
 (0.0002245963416094531, 'country_name_Indonesia'),
 (0.00022263897286773035, 'country_name_Kenya'),
 (0.00020823970252466942, 'country_name_Austria'),
 (0.00019842230286652468, 'country_name_Mauritania'),
 (0.00019773780658625132, 'country_name_Belarus'),
 (0.00019054397953516765, 'country_name_Portugal'),
 (0.00018830929367482567, 'country_name_Paraguay'),
 (0.00018709689777098674, 'country_name_Maldives'),
 (0.00016893520902646825, 'country_name_Jordan'),
 (0.00015484806824984235, 'country_name_Algeria'),
 (0.00013466112298867673, 'country_name_Bangladesh'),
 (0.00012728565338172824, 'country_name_Mali'),
 (0.00012115200965044408, 'country_name_Madagascar'),
 (0.00012007312953053487, 'country_name_Albania'),
 (0.00010627182513368799, 'country_name_Swaziland'),
 (7.810539856145146e-05, 'country_name_Estonia'),
 (7.328574280620328e-05, 'country_name_Spain'),
 (6.359685716411239e-05, 'country_name_Australia'),
 (5.928002036052598e-05, 'country_name_Egypt'),
 (5.635597580294879e-05, 'country_name_Ethiopia'),
 (5.4424085834376464e-05, 'country_name_Sweden'),
 (5.1381309860816904e-05, 'country_name_Russia'),
 (4.311607713616025e-05, 'country_name_Romania'),
 (2.1017571095153605e-05, 'country_name_Saudi Arabia'),
 (1.863516953206452e-05, 'country_name_Vietnam'),
 (1.0079895247550338e-06, 'country_name_Burkina Faso'),
 (0.0, 'ladder_score_distopia'),
 (0.0, 'country_name_Zambia'),
 (0.0, 'country_name_United Kingdom'),
 (0.0, 'country_name_Turkmenistan'),
 (0.0, 'country_name_Thailand'),
 (0.0, 'country_name_Tajikistan'),
 (0.0, 'country_name_South Africa'),
 (0.0, 'country_name_Slovenia'),
 (0.0, 'country_name_Slovakia'),
 (0.0, 'country_name_Singapore'),
 (0.0, 'country_name_Senegal'),
 (0.0, 'country_name_Panama'),
 (0.0, 'country_name_Norway'),
 (0.0, 'country_name_North Macedonia'),
 (0.0, 'country_name_North Cyprus'),
 (0.0, 'country_name_Nicaragua'),
 (0.0, 'country_name_Morocco'),
 (0.0, 'country_name_Mexico'),
 (0.0, 'country_name_Luxembourg'),
 (0.0, 'country_name_Liberia'),
 (0.0, 'country_name_Lesotho'),
 (0.0, 'country_name_Kyrgyzstan'),
 (0.0, 'country_name_Kazakhstan'),
 (0.0, 'country_name_Ivory Coast'),
 (0.0, 'country_name_Ireland'),
 (0.0, 'country_name_Iran'),
 (0.0, 'country_name_Honduras'),
 (0.0, 'country_name_Guatemala'),
 (0.0, 'country_name_Georgia'),
 (0.0, 'country_name_Gabon'),
 (0.0, 'country_name_El Salvador'),
 (0.0, 'country_name_Croatia'),
 (0.0, 'country_name_Comoros'),
 (0.0, 'country_name_Colombia'),
 (0.0, 'country_name_Chile'),
 (0.0, 'country_name_Chad'),
 (0.0, 'country_name_Cameroon'),
 (0.0, 'country_name_Botswana'),
 (0.0, 'country_name_Benin'),
 (0.0, 'country_name_Belgium'),
 (0.0, 'country_name_Azerbaijan')]